# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(868, 673)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sensitiveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.sensitiveBtn.setObjectName("sensitiveBtn")
        self.horizontalLayout.addWidget(self.sensitiveBtn)
        self.deleteCol = QtWidgets.QPushButton(self.centralwidget)
        self.deleteCol.setObjectName("deleteCol")
        self.horizontalLayout.addWidget(self.deleteCol)
        self.uniqueBtn = QtWidgets.QPushButton(self.centralwidget)
        self.uniqueBtn.setObjectName("uniqueBtn")
        self.horizontalLayout.addWidget(self.uniqueBtn)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.k_val = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.k_val.setFont(font)
        self.k_val.setMinimum(2)
        self.k_val.setMaximum(5)
        self.k_val.setSingleStep(1)
        self.k_val.setProperty("value", 2)
        self.k_val.setObjectName("k_val")
        self.horizontalLayout_2.addWidget(self.k_val)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.l_val = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.l_val.setFont(font)
        self.l_val.setMaximum(5)
        self.l_val.setProperty("value", 1)
        self.l_val.setObjectName("l_val")
        self.horizontalLayout_2.addWidget(self.l_val)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 868, 26))
        self.menubar.setObjectName("menubar")
        self.anonymization = QtWidgets.QMenu(self.menubar)
        self.anonymization.setObjectName("anonymization")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.noise = QtWidgets.QAction(MainWindow)
        self.noise.setObjectName("noise")
        self.microaggregation = QtWidgets.QAction(MainWindow)
        self.microaggregation.setObjectName("microaggregation")
        self.suppresion = QtWidgets.QAction(MainWindow)
        self.suppresion.setObjectName("suppresion")
        self.randomization = QtWidgets.QAction(MainWindow)
        self.randomization.setObjectName("randomization")
        self.generalization = QtWidgets.QAction(MainWindow)
        self.generalization.setObjectName("generalization")
        self.openAction = QtWidgets.QAction(MainWindow)
        self.openAction.setObjectName("openAction")
        self.saveAction = QtWidgets.QAction(MainWindow)
        self.saveAction.setObjectName("saveAction")
        self.anonymization.addAction(self.noise)
        self.anonymization.addAction(self.microaggregation)
        self.anonymization.addAction(self.suppresion)
        self.anonymization.addAction(self.randomization)
        self.anonymization.addAction(self.generalization)
        self.menu.addAction(self.openAction)
        self.menu.addAction(self.saveAction)
        self.menubar.addAction(self.anonymization.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sensitiveBtn.setText(_translate("MainWindow", "Столбец с чувствительным атрибутом"))
        self.deleteCol.setText(_translate("MainWindow", "Удалить столбцы"))
        self.uniqueBtn.setText(_translate("MainWindow", "Найти уникальные строки"))
        self.label.setText(_translate("MainWindow", "k-анонимность"))
        self.label_2.setText(_translate("MainWindow", "L-разнообразие"))
        self.anonymization.setTitle(_translate("MainWindow", "Методы"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.noise.setText(_translate("MainWindow", "Добавить шум"))
        self.microaggregation.setText(_translate("MainWindow", "Микроаггрегация"))
        self.suppresion.setText(_translate("MainWindow", "Локальное подавление"))
        self.randomization.setText(_translate("MainWindow", "Пост-рандомизация"))
        self.generalization.setText(_translate("MainWindow", "Обобщение"))
        self.openAction.setText(_translate("MainWindow", "Открыть"))
        self.saveAction.setText(_translate("MainWindow", "Сохранить"))

