# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'noise.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddNoise(object):
    def setupUi(self, AddNoise):
        AddNoise.setObjectName("AddNoise")
        AddNoise.resize(620, 300)
        self.gridLayout = QtWidgets.QGridLayout(AddNoise)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(AddNoise)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 8, 0, 1, 1)
        self.roundCheckBox = QtWidgets.QCheckBox(AddNoise)
        self.roundCheckBox.setObjectName("roundCheckBox")
        self.gridLayout.addWidget(self.roundCheckBox, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn1 = QtWidgets.QRadioButton(AddNoise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn1.sizePolicy().hasHeightForWidth())
        self.btn1.setSizePolicy(sizePolicy)
        self.btn1.setChecked(True)
        self.btn1.setObjectName("btn1")
        self.horizontalLayout.addWidget(self.btn1)
        self.btn2 = QtWidgets.QRadioButton(AddNoise)
        self.btn2.setChecked(False)
        self.btn2.setObjectName("btn2")
        self.horizontalLayout.addWidget(self.btn2)
        self.btn3 = QtWidgets.QRadioButton(AddNoise)
        self.btn3.setObjectName("btn3")
        self.horizontalLayout.addWidget(self.btn3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(AddNoise)
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.stdSpinBox = QtWidgets.QDoubleSpinBox(self.widget1)
        self.stdSpinBox.setMinimum(0.1)
        self.stdSpinBox.setMaximum(1.0)
        self.stdSpinBox.setSingleStep(0.05)
        self.stdSpinBox.setProperty("value", 0.2)
        self.stdSpinBox.setObjectName("stdSpinBox")
        self.horizontalLayout_2.addWidget(self.stdSpinBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget1, 1, 0, 1, 1)
        self.widget3 = QtWidgets.QWidget(AddNoise)
        self.widget3.setObjectName("widget3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.widget3)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.startSpinBox = QtWidgets.QDoubleSpinBox(self.widget3)
        self.startSpinBox.setMinimum(-100000.0)
        self.startSpinBox.setMaximum(100000.0)
        self.startSpinBox.setSingleStep(0.1)
        self.startSpinBox.setProperty("value", -10.0)
        self.startSpinBox.setObjectName("startSpinBox")
        self.horizontalLayout_3.addWidget(self.startSpinBox)
        self.label_3 = QtWidgets.QLabel(self.widget3)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.endSpinBox = QtWidgets.QDoubleSpinBox(self.widget3)
        self.endSpinBox.setMinimum(-100000.0)
        self.endSpinBox.setMaximum(100000.0)
        self.endSpinBox.setSingleStep(0.1)
        self.endSpinBox.setProperty("value", 10.0)
        self.endSpinBox.setObjectName("endSpinBox")
        self.horizontalLayout_3.addWidget(self.endSpinBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget3, 3, 0, 1, 1)
        self.widget2 = QtWidgets.QWidget(AddNoise)
        self.widget2.setObjectName("widget2")
        self.gridLayout.addWidget(self.widget2, 2, 0, 1, 1)

        self.retranslateUi(AddNoise)
        self.buttonBox.accepted.connect(AddNoise.accept)
        self.buttonBox.rejected.connect(AddNoise.reject)
        QtCore.QMetaObject.connectSlotsByName(AddNoise)

    def retranslateUi(self, AddNoise):
        _translate = QtCore.QCoreApplication.translate
        AddNoise.setWindowTitle(_translate("AddNoise", "Добавить шум"))
        self.roundCheckBox.setText(_translate("AddNoise", "Округлять значения"))
        self.btn1.setText(_translate("AddNoise", "Гауссов шум"))
        self.btn2.setText(_translate("AddNoise", "Мультипликативный шум"))
        self.btn3.setText(_translate("AddNoise", "Равномерный шум"))
        self.label.setText(_translate("AddNoise", "Множитель стандартного отклонения"))
        self.label_2.setText(_translate("AddNoise", "От:"))
        self.label_3.setText(_translate("AddNoise", "До:"))

